### ISSUE TITLE
ANCHOR_CLASS and DEV mode

### ISSUE THREAD

**Issue by Jerom138** [KleeGroup/webpack-focus#5]
webpack.config.js :
```javascript
   __ANCHOR_CLASS__: DEV ? JSON.stringify(ANCHOR_CLASS) : null,
```

The application can be render in a DIV (anchor) only in DEV mode.

**Comment by pierr** [comment]
Fixed in 5f278fac812c1cd8a0a504792f8a14cba631ab0d
